###
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "id": 3,
  "author": "DolphaGo",
  "title": "test title~~~~~~~~~~~~~",
  "content": "test content~~~"
}

###
GET http://localhost:8080/api/v1/posts

<> 2022-06-19T000318.200.json
<> 2022-06-19T000258.200.json

